Troubleshooting odd module not available message
Upgraded Angular to 1.4.0 beta.6. Now, it claims modules won't load.
Trying some things. Error:
Uncaught Error: [$injector:modulerr] Failed to instantiate module owen
due to:
Error: [$injector:modulerr] Failed to instantiate module
owen.chat due to:
Error: [$injector:nomod] Module 'owen.chat' is not
available! You either misspelled the module name or forgot to load it.
If registering a module ensure that you specify the dependencies as the
second argument.